#!/bin/bash
echo "Set env vars"
export MAVEN_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.9
export M2_REPO=$OPENSHIFT_DATA_DIR/maven-repo
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_112
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
cd $OPENSHIFT_REPO_DIR
echo "Build war"
mvn install -P openshift
echo "Deploy War"
cp $OPENSHIFT_REPO_DIR/target/wedding.war $OPENSHIFT_DATA_DIR/apache-tomcat-8.5.8/webapps/wedding.war
cd $OPENSHIFT_DATA_DIR/apache-tomcat-8.5.8/bin
./startup.sh